"""add candidate profile fields

Revision ID: 06bfc42291fe
Revises: d5df1b749726
Create Date: 2025-12-20 15:45:52.682335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06bfc42291fe'
down_revision: Union[str, Sequence[str], None] = 'd5df1b749726'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('full_name', sa.String(length=255), nullable=True, comment='ФИО соискателя'))
    op.add_column('candidates', sa.Column('age', sa.Integer(), nullable=True, comment='Возраст'))
    op.add_column('candidates', sa.Column('skills', sa.Text(), nullable=True, comment='Навыки (через запятую или текстом)'))
    op.add_column('candidates', sa.Column('current_company', sa.String(length=255), nullable=True, comment='Текущее место работы'))
    op.add_column('candidates', sa.Column('resume_file_id', sa.String(length=255), nullable=True, comment='Telegram file_id резюме'))
    op.add_column('candidates', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('candidates', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'updated_at')
    op.drop_column('candidates', 'created_at')
    op.drop_column('candidates', 'resume_file_id')
    op.drop_column('candidates', 'current_company')
    op.drop_column('candidates', 'skills')
    op.drop_column('candidates', 'age')
    op.drop_column('candidates', 'full_name')
    # ### end Alembic commands ###
