"""add recruiter status and vacancy fields

Revision ID: 2146745fe696
Revises: a3d1feea3fb5
Create Date: 2025-12-21 13:56:13.070039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2146745fe696'
down_revision: Union[str, Sequence[str], None] = 'a3d1feea3fb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recruiters', sa.Column('status', sa.String(length=16), server_default='pending', nullable=False))
    op.add_column('recruiters', sa.Column('full_name_position', sa.String(length=255), nullable=True, comment='ФИО и должность рекрутера для связи'))
    op.add_column('recruiters', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('recruiters', 'user_id',
               existing_type=sa.UUID(),
               comment='Связь с users.id',
               existing_nullable=False)
    op.drop_constraint(op.f('recruiters_user_id_fkey'), 'recruiters', type_='foreignkey')
    op.add_column('vacancies', sa.Column('salary_from', sa.Integer(), nullable=True))
    op.add_column('vacancies', sa.Column('salary_to', sa.Integer(), nullable=True))
    op.add_column('vacancies', sa.Column('city', sa.String(length=128), nullable=True))
    op.add_column('vacancies', sa.Column('is_remote', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancies', 'is_remote')
    op.drop_column('vacancies', 'city')
    op.drop_column('vacancies', 'salary_to')
    op.drop_column('vacancies', 'salary_from')
    op.create_foreign_key(op.f('recruiters_user_id_fkey'), 'recruiters', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('recruiters', 'user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Связь с users.id',
               existing_nullable=False)
    op.drop_column('recruiters', 'created_at')
    op.drop_column('recruiters', 'full_name_position')
    op.drop_column('recruiters', 'status')
    # ### end Alembic commands ###
