"""add recruiter and candidate

Revision ID: 6a387ba06fea
Revises: e747ea9ed843
Create Date: 2025-12-15 15:55:47.580936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a387ba06fea'
down_revision: Union[str, Sequence[str], None] = 'e747ea9ed843'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
                    sa.Column(
                        'id',
                        sa.UUID(),
                        server_default=sa.text('gen_random_uuid()'),
                        nullable=False
                    ),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('recruiters',
                    sa.Column(
                        'id',
                        sa.UUID(),
                        server_default=sa.text('gen_random_uuid()'),
                        nullable=False
                    ),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('recruiter_companies',
    sa.Column('recruiter_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recruiter_id'], ['recruiters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recruiter_id', 'company_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recruiter_companies')
    op.drop_table('recruiters')
    op.drop_table('candidates')
    # ### end Alembic commands ###
