"""update recruiters fields

Revision ID: 78fee0485254
Revises: d19caac6a18b
Create Date: 2025-12-21 15:31:03.535963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78fee0485254'
down_revision: Union[str, Sequence[str], None] = 'd19caac6a18b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('companies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('recruiters', sa.Column('full_name', sa.String(length=255), nullable=True, comment='ФИО рекрутера'))
    op.add_column('recruiters', sa.Column('position', sa.String(length=255), nullable=True, comment='Должность'))
    op.add_column('recruiters', sa.Column('is_approved', sa.Boolean(), server_default='false', nullable=False, comment='Одобрен ли админом'))
    op.alter_column('recruiters', 'user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Связь с users.id',
               existing_nullable=False)
    op.create_foreign_key(None, 'recruiters', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('recruiters', 'status')
    op.drop_column('recruiters', 'full_name_position')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('recruiters', sa.Column('full_name_position', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='ФИО и должность рекрутера для связи'))
    op.add_column('recruiters', sa.Column('status', sa.VARCHAR(length=16), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'recruiters', type_='foreignkey')
    op.alter_column('recruiters', 'user_id',
               existing_type=sa.UUID(),
               comment='Связь с users.id',
               existing_nullable=False)
    op.drop_column('recruiters', 'is_approved')
    op.drop_column('recruiters', 'position')
    op.drop_column('recruiters', 'full_name')
    op.alter_column('companies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('companies', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###
