"""update 15:37

Revision ID: a3bce27f9e49
Revises: 78fee0485254
Create Date: 2025-12-21 15:37:29.124938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3bce27f9e49'
down_revision: Union[str, Sequence[str], None] = '78fee0485254'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recruiter_applications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('application_number', sa.Integer(), nullable=False, comment='Порядковый номер заявки для отображения'),
    sa.Column('recruiter_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False, comment='Компания, в которую подается заявка'),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False, comment='pending | approved | rejected'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True, comment='Когда рассмотрена'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recruiter_id'], ['recruiters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recruiter_applications')
    # ### end Alembic commands ###
