"""add admin whitelist

Revision ID: a3d1feea3fb5
Revises: 06bfc42291fe
Create Date: 2025-12-20 17:58:43.605748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3d1feea3fb5'
down_revision: Union[str, Sequence[str], None] = '06bfc42291fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_whitelist',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False, comment='Telegram ID администратора (whitelist)'),
    sa.Column('note', sa.String(length=255), nullable=True, comment='Комментарий (кто это / зачем добавлен)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_whitelist')
    # ### end Alembic commands ###
